#
# you can validate this file ahead of time: http://lint.travis-ci.org/

language: python

python:
    - 3.5

env:
    global:
        - NUMPY_VERSION=1.11

matrix:
    include:
        - python: 3.3
          env: NUMPY_VERSION=1.7
        - python: 3.4
          env: NUMPY_VERSION=1.9

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION pytest
    - source activate test
    - python setup.py install

script: py.test
